export const UPLOAD_LOADING = 'UPLOAD_LOADING';
export const UPLOAD_LOADING_SUCCESS = 'UPLOAD_LOADING_SUCCESS';
export const UPLOAD_LOADING_FAILURE = 'UPLOAD_LOADING_FAILURE';

export const REMOVE_UPLOAD = 'REMOVE_UPLOAD';
